sudo: required
services:
  - docker

before_install:
  - docker build -t docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-2"
  bucket_name: "elasticbeanstalk-us-east-1-825382296107"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
